### ISSUE TITLE
How to limit the topics that a user can access/see?

### ISSUE THREAD

**Issue by HugoFelgueirasCF** [CorefluxCommunity/Coreflux-fluxassets#2]
### Bug Description 🐞

I'm using a online Broker from Coreflux, and I already added some users there in order to manage different information access. How can I manage what topics each of the users are allowed to see?

### Steps to Reproduce 🔄

Add different users to the same broker.

### Expected Behavior ✅

I would expect that different users accessing the Online Broker would be allowed to see only the specific topics assigned to him.

### Environment 🌐

Windows 10

### Asset Type 🧩

Docker Orchestrator

### Terms of Service

- [X] I agree to the terms and conditions

**Comment by HugoAVaz** [comment]
This issue is not related to docker orchestration. Also this is not a bug. I would have to remove this and close this issue.
