### ISSUE TITLE
[BUG] - EthernetIPMQTT Asset with several issues

### ISSUE THREAD

**Issue by 96DrQ** [CorefluxCommunity/Coreflux-fluxassets#7]
### Bug Description 🐞

I'm experiencing several issues:
- I'm not being able to write values into the device;
- I'm not being able to read values that are being sent by the device in the same atribute

### Steps to Reproduce 🔄

I already tried to write values into the device but with no success. I tried to write different types of values but without success. Can I be doing something wrong or do I need to do any activation or modification in the device?

When I read the values from my device they are alocated to the same class and instance and then inside the first atribute I get access to an array where I can see all the values being sent by the device. Is there a way for me to map this array into different topics and map the byte number of that array and the asset to read the value according to the variable type that I defined?

### Expected Behavior ✅

To write values into the device.

to be able to read multiple variables from an array list

### Environment 🌐

Windows 10

### Asset Type 🧩

Ethernet/IP

### Terms of Service

- [x] I agree to the terms and conditions

AB#389

**Comment by RafaelVieira-Coreflux** [comment]
Hello @96DrQ  thank you for your issue ticket.

Our team has just delivered a huge update regarding the Ethernet/IP asset. Everything is working as expected now.

Please test it and let us know your feedback.

For more detailed information, feel free to check out our documentation at the link below:
[Coreflux Ethernet/IP docs](https://docs.coreflux.org/flux-assets/connectors/ethernetip/)

Best regards,
Rafael Soares, Backend developer

**Comment by RafaelVieira-Coreflux** [comment]
Hello @96DrQ thank you for your issue ticket.

Our team has just delivered a huge update regarding the Ethernet/IP asset. Everything is working as expected now.

Please test it and let us know your feedback.

For more detailed information, feel free to check out our documentation at the link below:
[Coreflux Ethernet/IP docs](https://docs.coreflux.org/flux-assets/connectors/ethernetip/)

Best regards,
Rafael Soares, Backend developer
